name: Evolene CI

on: push
jobs:
  Evolene:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run Evolene CI pipeline steps
        shell: bash
        env:
          SLACK_CHANNELS: "#team-e-larande-build"
          SKIP_DRY_RUN: True

        run: |
          ${{ secrets.EVOLENE_RUN_COMMAND }}
